spring:
  datasource:
    url: jdbc:mysql://localhost/db_springboot_backend?serverTimezone=UTC
    username: devtest
    password: MySQL*2019
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: America/Bogota
    locale: es_CO
                   
logging:
  level:
    org.hibernate.sql: debug
    