insert into zone (id, name) values (1,'South America');
insert into zone (id, name) values (2,'North America');
insert into zone (id, name) values (3,'Central America');
insert into zone (id, name) values (4,'Europe');
insert into zone (id, name) values (5,'Asia');
insert into zone (id, name) values (6,'Africa');
insert into zone (id, name) values (7,'Oceania');
insert into zone (id, name) values (8,'Antarctica');



insert into client (first_name, last_name, email, created_at, zone_id) values ('Pepito', 'Pérez', 'pepito@mail.co', '2019-06-27', 1);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Camilo', 'Méndez', 'camilo@mail.co', '2019-06-27', 2);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Andrés', 'Gómez', 'andres@mail.co', '2019-06-27', 3);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Felipe', 'Parra', 'felipe@mail.co', '2019-06-27', 4);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Carlos', 'Melo', 'carlos@mail.co', '2019-06-27', 5);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Juan', 'Ramos', 'juan@mail.co', '2019-06-27', 6);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Fernando', 'Rodríguez', 'fernando@mail.co', '2019-06-27', 7);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Sandra', 'López', 'sandra@mail.co', '2019-06-27', 8);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Johanna', 'Romero', 'johanna@mail.co', '2019-06-27', 8);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Maria', 'Medina', 'maria@mail.co', '2019-06-27', 5);
insert into client (first_name, last_name, email, created_at, zone_id) values ('José', 'Mora', 'jose@mail.co', '2019-06-27', 8);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Miguel', 'Sandoval', 'miguel@mail.co', '2019-06-27', 7);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client1', 'Client1', 'client1@mail.co', '2019-07-02', 6);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client2', 'Client2', 'Client2@mail.co', '2019-07-02', 5);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client3', 'Client3', 'Client3@mail.co', '2019-07-02', 4);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client4', 'Client4', 'Client4@mail.co', '2019-07-02', 3);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client5', 'Client5', 'Client5@mail.co', '2019-07-02', 2);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client6', 'Client6', 'Client6@mail.co', '2019-07-02', 1);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client7', 'Client7', 'Client7@mail.co', '2019-07-02', 1);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client8', 'Client8', 'Client8@mail.co', '2019-07-02', 2);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client9', 'Client9', 'Client9@mail.co', '2019-07-02', 3);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client10', 'Client10', 'Client10@mail.co', '2019-07-02', 4);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client11', 'Client11', 'Client11@mail.co', '2019-07-02', 5);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client12', 'Client12', 'Client12@mail.co', '2019-07-02', 6);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client13', 'Client13', 'Client13@mail.co', '2019-07-02', 7);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client14', 'Client14', 'Client14@mail.co', '2019-07-02', 8);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client15', 'Client15', 'Client15@mail.co', '2019-07-02', 1);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client16', 'Client16', 'Client16@mail.co', '2019-07-02', 2);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client17', 'Client17', 'Client17@mail.co', '2019-07-02', 3);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client18', 'Client18', 'Client18@mail.co', '2019-07-02', 4);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client19', 'Client19', 'Client19@mail.co', '2019-07-02', 5);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client20', 'Client20', 'Client20@mail.co', '2019-07-02', 6);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client21', 'Client21', 'Client21@mail.co', '2019-07-02', 7);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client22', 'Client22', 'Client22@mail.co', '2019-07-02', 8);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client23', 'Client23', 'Client23@mail.co', '2019-07-02', 8);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client24', 'Client24', 'Client24@mail.co', '2019-07-02', 7);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client25', 'Client25', 'Client25@mail.co', '2019-07-02', 6);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client26', 'Client26', 'Client26@mail.co', '2019-07-02', 5);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client27', 'Client27', 'Client27@mail.co', '2019-07-02', 4);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client28', 'Client28', 'Client28@mail.co', '2019-07-02', 3);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client29', 'Client29', 'Client29@mail.co', '2019-07-02', 2);
insert into client (first_name, last_name, email, created_at, zone_id) values ('Client30', 'Client30', 'Client30@mail.co', '2019-07-02', 1);